### ISSUE TITLE
Russound RIO NS has a reoccurring WATCH error

### ISSUE THREAD

**Issue by gbix1966** [Jimk72/RussoundRIO#1]
Hi
I keep receiving this error on the Polisy running the Russound RIO node server. It may run for as long as two days but will eventually fail with this error. Just Watch stops running.  Russound MC5.

2021-06-21 03:08:46,176 Thread-1   polyinterface      ERROR    polyinterface:write: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/polyglot/nodeservers/RussoundRIO/russound_main.py", line 68, in MessageLoop
    self.__russound_loop_tcp(processCommand)
  File "/var/polyglot/nodeservers/RussoundRIO/russound_main.py", line 58, in __russound_loop_tcp
    processCommand(x.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 27: invalid start byte

Thanks Gary

**Comment by Jimk72** [comment]
I will take a look this weekend and see if I can fix this.
